name:                moore
version:             0.1.0.0
github:              "cspollard/moore"
license:             BSD3
author:              "Chris Pollard"
maintainer:          "cspollard@gmail.com.com"
copyright:           "2019 Chris Pollard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/moore#readme>

default-extensions:
- RankNTypes
- ScopedTypeVariables
- TupleSections
- DerivingVia
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveGeneric
- PatternSynonyms

dependencies:
- base >= 4.7 && < 5
- profunctors
- bifunctors
- lens
- semigroupoids
- cereal

library:
  source-dirs: src
